# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ffc1f7e179fb7840ab3fccae8ae7eaa390b0721fba585871a93579b7a585ea3dcea2f1b93d80ce2088a872c266835c088e4ab74533f213e12212cda347817ef

test:
  secret_key_base: 886ca79a73dc1c5c16dcaa9145f766d7aa7ed526164801dda7d71a774ef6ed711b8a4413cc62250afe422b703e33ea0e80f42fd9ee6ed28a11fa57ee65fa75a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
